targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          outputDirectory: generated/output
          assetsPath: "lib/generated/input/**.graphql"
